package demo.entities;
// Generated Oct 17, 2016 11:45:05 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bcc generated by hbm2java
 */
@Entity
@Table(name = "bcc", catalog = "db_stock")
public class Bcc implements java.io.Serializable {

	private Date thoiGian;
	private double gia;
	private int khoiLuongLo;
	private int khoiLuongTichLuy;
	private double tyTrong;

	public Bcc() {
	}

	public Bcc(Date thoiGian, double gia, int khoiLuongLo, int khoiLuongTichLuy, double tyTrong) {
		this.thoiGian = thoiGian;
		this.gia = gia;
		this.khoiLuongLo = khoiLuongLo;
		this.khoiLuongTichLuy = khoiLuongTichLuy;
		this.tyTrong = tyTrong;
	}

	@Id

	@Temporal(TemporalType.DATE)
	@Column(name = "ThoiGian", unique = true, nullable = false, length = 10)
	public Date getThoiGian() {
		return this.thoiGian;
	}

	public void setThoiGian(Date thoiGian) {
		this.thoiGian = thoiGian;
	}

	@Column(name = "Gia", nullable = false, precision = 22, scale = 0)
	public double getGia() {
		return this.gia;
	}

	public void setGia(double gia) {
		this.gia = gia;
	}

	@Column(name = "KhoiLuongLo", nullable = false)
	public int getKhoiLuongLo() {
		return this.khoiLuongLo;
	}

	public void setKhoiLuongLo(int khoiLuongLo) {
		this.khoiLuongLo = khoiLuongLo;
	}

	@Column(name = "KhoiLuongTichLuy", nullable = false)
	public int getKhoiLuongTichLuy() {
		return this.khoiLuongTichLuy;
	}

	public void setKhoiLuongTichLuy(int khoiLuongTichLuy) {
		this.khoiLuongTichLuy = khoiLuongTichLuy;
	}

	@Column(name = "TyTrong", nullable = false, precision = 22, scale = 0)
	public double getTyTrong() {
		return this.tyTrong;
	}

	public void setTyTrong(double tyTrong) {
		this.tyTrong = tyTrong;
	}

}
